spring.application.name=EjadWebApplication

spring.datasource.url=jdbc:mysql://localhost:3306/ejad
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

gemini.api.key=${GEMINI_API_KEY}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

openai.api.key=${OPENAI_API_KEY}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

gemini.api.key=${GEMINI_API_KEY}
ai.model=gemini-3.5-flash-lite
google.maps.api.key=${GOOGLE_MAPS_API_KEY:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eazmirara@gmail.com
spring.mail.password=ovpprmworwslzxaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
